# Generated by Django 4.2.16 on 2024-10-16 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('biographie', models.TextField()),
                ('date_de_naissance', models.DateField()),
                ('date_de_deces', models.DateField(blank=True, null=True)),
                ('nationalite', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Editeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('adresse', models.CharField(max_length=255)),
                ('site_web', models.URLField()),
                ('email_contact', models.EmailField(max_length=254)),
                ('description', models.TextField()),
                ('logo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('resume', models.TextField()),
                ('date_de_publication', models.DateField()),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('nombre_de_pages', models.IntegerField()),
                ('langue', models.CharField(max_length=50)),
                ('image_de_couverture', models.TextField()),
                ('auteurs', models.ManyToManyField(to='gestion.auteur')),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Exemplaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etat', models.CharField(max_length=50)),
                ('date_acquisition', models.DateField()),
                ('localisation', models.CharField(max_length=255)),
                ('disponibilite', models.BooleanField(default=True)),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.livre')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField()),
                ('commentaire', models.TextField()),
                ('date_evaluation', models.DateTimeField(auto_now_add=True)),
                ('recommande', models.BooleanField(default=False)),
                ('titre', models.CharField(max_length=255)),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.livre')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Emprunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_emprunt', models.DateTimeField(auto_now_add=True)),
                ('date_retour_prevue', models.DateTimeField()),
                ('date_retour_effective', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(max_length=50)),
                ('remarques', models.TextField(blank=True, null=True)),
                ('exemplaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.exemplaire')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('note', models.IntegerField()),
                ('visible', models.BooleanField(default=True)),
                ('modere', models.BooleanField(default=False)),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.livre')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
